using JuMP, AxisArrays, Gurobi, UnPack, StatsPlots, Colors, Statistics, PrettyTables, DataFrames, Plots

include("Input.jl")
include("Helpfunctions.jl")

#//////////////////////////////////////////////////////////////////////////////////////////////////
"""
Build_Stochastic_Model(problem, input, scenario_data)

Construct the JuMP stochastic optimization model.
- `problem` contains model options and parameters
- `input` contains prepared inputs and static tables
- `scenario_data` contains scenario-level time series (CF, load, inflows) and probabilities

Returns a named tuple with the model and references to important JuMP variables (Capacity, Electricity, TransmissionCapacity, etc.).
"""
function Build_Stochastic_Model(problem, input, scenario_data)
    @unpack REGION, PLANT, TECH, PERIOD, no_periods, no_regions, no_plants, no_techs, inv_cost, fixed_cost, var_cost, fuel_cost, eta, discharge_time,
        emissionfactor, crf, maxcap, hydroreservoir, PSopenReservoir, PSclosedReservoir, min_reservoir_level, transmissioncost, distance, valid_links, max_transmission, loss_per_K_Km, crf_t = input
    @unpack SCENARIO, load, cf, res_inflow, ror_inflow, PS_inflow, prob = scenario_data 
    @unpack carbon_cap, storage, transmission, transmission_constrained, nuclear, time_step, load_shedding_cost, planned_outage_rate, load_shedding_ratio, fix_hydro = problem
    println("\nBuilding models...")
 
    m = Model(Gurobi.Optimizer)
    set_optimizer_attributes(m, "Threads" => 0, "Method"=> 2, "Crossover"=> 0, "TimeLimit" => 10000)

    
    @variables m begin
        # OperationalCost[s]: operational cost for scenario s (€/year)
        # FixedCost[s]: fixed (annualized) cost (€/year)
        # TotalSheddedLoadCost[s]: cost for load shedding in scenario s (€/year)
        # TotalEmissions[s]: total annual emissions in scenario s (ton CO2/year)
        # InvestmentCost: total annual investment cost (€/year)
        # Electricity[s,r,p,h]: Electricity generated by technology p in region r under scenario s at time step h (MWh)
        # SheddedLoad[s,r,h]: shedded load in region r under scenario s at time step h (MWh)
        # Capacity[r,p]: installed capacity for tech p in region r (MW); for Battery capacity is in MWh
        # ChargeLevel, ReservoirLevel, PSopen/closedLevel, H2StorageLevel: storage state variables (MWh)
        # Transmission and TransmissionCapacity: inter-regional flows (MWh) and line capacities (MW)
        # PlannedOutage[s,r,h]: planned outage power for nuclear plants (MW)

        OperationalCost[s in SCENARIO]                                           >= 0        # €
        FixedCost[s in SCENARIO]                                                 >= 0        # €
        TotalSheddedLoadCost[s in SCENARIO]                                      >= 0        # €
        TotalEmissions[s in SCENARIO]                                            >= 0        # ton CO2
        InvestmentCost                                                           >= 0        # €
        Electricity[s in SCENARIO, r in REGION, p in TECH, h in PERIOD]          >= 0        # MWh/h
        SheddedLoad[s in SCENARIO, r in REGION, h in PERIOD]                     >= 0        # MWh/h
        Capacity[r in REGION, p in TECH]                                         >= 0        # MW, MWh for Battery
        ChargeLevel[s in SCENARIO, r in REGION, h in PERIOD]                     >= 0        # MWh
        ReservoirLevel[s in SCENARIO, r in REGION, h in PERIOD]                  >= 0        # MWh
        PSopenLevel[s in SCENARIO, r in REGION, h in PERIOD]                     >= 0        # MWh  
        PSclosedLevel[s in SCENARIO, r in REGION, h in PERIOD]                   >= 0        # MWh 
        H2StorageLevel[s in SCENARIO, r in REGION, h in PERIOD]                  >= 0        # MWh
        Transmission[s in SCENARIO, r in REGION, r1 in REGION, h in PERIOD; valid_links[r, r1]]       >= 0        # MWh/h
        TransmissionCapacity[r in REGION, r1 in REGION; r1 > r && valid_links[r, r1]]                 >= 0        # MW	
        PlannedOutage[s in SCENARIO, r in REGION, h in PERIOD]                   >= 0        # MW 
    end #variables
    
    for r in REGION, p in TECH
        set_upper_bound(Capacity[r, p], maxcap[r, p])
    end

    if !storage
        for r in REGION
            set_upper_bound(Capacity[r,:Battery], 0.0)
        end
    end

    if !transmission
        for r in REGION
            for r1 in REGION
                if r1 > r && valid_links[r, r1] == true
                    set_upper_bound(TransmissionCapacity[r, r1], 0.0)
                end
            end
        end
    end

    # If the transmission grid is constrained, set upper bounds on transmission capacities
    if transmission_constrained
        for r in REGION
            for r1 in REGION
                if r1 > r && valid_links[r, r1] == true
                    set_upper_bound(TransmissionCapacity[r, r1], max_transmission[r, r1])
                end
            end
        end
    end

    if !nuclear
        for r in REGION
            set_upper_bound(Capacity[r, :Nuclear], 0.0)    
        end   
    end

    if fix_hydro
        for r in REGION, p in [:HydroRes, :HydroRoR, :PSHopenTurb, :PSHopenPump, :PSHclosedTurb, :PSHclosedPump]
            fix(Capacity[r, p], maxcap[r, p], force = true)
        end
    end

    @constraints m begin
        # ELECTRICITY GENERATION
        Generation_0[s in SCENARIO, r in REGION, p in PLANT, h in PERIOD; p != :Nuclear],
            Electricity[s, r, p, h] <= Capacity[r, p] * cf[s, r, p, h] * time_step

        Generation_1[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s, r, :Nuclear, h] <= Capacity[r, :Nuclear] * time_step - PlannedOutage[s, r, h]

        # BATTERIES & INVERTER
        InverterCapacity[s in SCENARIO, r in REGION, h in PERIOD], 
            Electricity[s, r, :Inverter, h] + Electricity[s, r, :Battery, h] <= Capacity[r, :Inverter] * time_step

        ChargeDischargeCapacity[r in REGION],
            discharge_time * Capacity[r, :Inverter] <= Capacity[r, :Battery]

        StorageSize[s in SCENARIO, r in REGION, h in PERIOD],
            ChargeLevel[s, r, h] <= Capacity[r, :Battery]

        ElecStorageBalance[s in SCENARIO, r in REGION, h in PERIOD],
            ChargeLevel[s, r, h] <= ChargeLevel[s, r, h>1 ? h-1 : length(PERIOD)] + eta[:Inverter] * Electricity[s, r, :Battery, h] +
            - Electricity[s, r, :Inverter, h]/eta[:Inverter]

        # ELECTRICITY TRANSMISSION
        ElecTransmission[s in SCENARIO, r in REGION, r1 in REGION, h in PERIOD; r1 > r && valid_links[r, r1]], 
        	Transmission[s, r, r1, h] + Transmission[s, r1, r, h] <= TransmissionCapacity[r, r1]* time_step

        # NUCLEAR
        OutagePlanned[s in SCENARIO, r in REGION],
            sum(PlannedOutage[s, r, h] for h in PERIOD) == planned_outage_rate * no_periods * Capacity[r, :Nuclear] * time_step 

        # HYDROPOWER RESERVOIR
        ReservoirBalance[s in SCENARIO, r in REGION, h in PERIOD],
           ReservoirLevel[s, r, h] <= ReservoirLevel[s, r, h>1 ? h-1 : length(PERIOD)] + res_inflow[s, r, h] * time_step +
            - Electricity[s, r, :HydroRes, h] / eta[:HydroRes]

        ReservoirSize[s in SCENARIO, r in REGION, h in PERIOD],
            ReservoirLevel[s, r, h] <= hydroreservoir[r] * 1e6

        MinReservoirLevel[s in SCENARIO, r in REGION, h in PERIOD],
            ReservoirLevel[s, r, h] >= min_reservoir_level[r] * hydroreservoir[r] * 1e6

        # HYDROPOWER ROR
        HydroRoRGeneration[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s, r, :HydroRoR, h] <= ror_inflow[s, r, h] * time_step
        
        # PUMPED STORAGE HYDROPOWER
        PSopenBalance[s in SCENARIO, r in REGION, h in PERIOD],
            PSopenLevel[s,r,h] <= PSopenLevel[s, r, h>1 ? h-1 : length(PERIOD)] + 
            + Electricity[s,r,:PSHopenPump,h] * eta[:PSHopenPump] - Electricity[s,r,:PSHopenTurb,h] / eta[:PSHopenTurb] + PS_inflow[s,r,h] * time_step
            
        PSclosedBalance[s in SCENARIO, r in REGION, h in PERIOD],
            PSclosedLevel[s,r,h] <= PSclosedLevel[s, r, h>1 ? h-1 : length(PERIOD)] +
            + Electricity[s,r,:PSHclosedPump,h] * eta[:PSHclosedPump] - Electricity[s,r,:PSHclosedTurb,h] / eta[:PSHclosedTurb]
        
        
        PowerBoundsPSHopenTurb[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s,r,:PSHopenTurb,h] <= Capacity[r, :PSHopenTurb] * time_step

        PowerBoundsPSHopenPump[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s,r,:PSHopenPump,h] <= Capacity[r, :PSHopenPump] * time_step

        PowerBoundsPSHclosedTurb[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s,r,:PSHclosedTurb,h] <= Capacity[r, :PSHclosedTurb] * time_step

        PowerBoundsPSHclosedPump[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s,r,:PSHclosedPump,h] <= Capacity[r, :PSHclosedPump] * time_step
        

        PSopenReservoirSize[s in SCENARIO, r in REGION, h in PERIOD],
            PSopenLevel[s, r, h] <= PSopenReservoir[r] * 1e6     # [MWh]

        PSclosedReservoirSize[s in SCENARIO, r in REGION, h in PERIOD],
            PSclosedLevel[s, r, h] <= PSclosedReservoir[r] * 1e6     # [MWh]

            
        MinPSopenReservoirLevel[s in SCENARIO, r in REGION, h in PERIOD],
            PSopenLevel[s, r, h] >= min_reservoir_level[r] * PSopenReservoir[r] * 1e6

        # HYDROGEN
        PowerBoundsH2GT[s in SCENARIO, r in REGION, h in PERIOD],
			Electricity[s,r,:H2GT,h] <= Capacity[r,:H2GT] * time_step

        PowerBoundsElectrolyzer[s in SCENARIO, r in REGION, h in PERIOD],
            Electricity[s,r,:Electrolyzer,h] * eta[:Electrolyzer] <= Capacity[r,:Electrolyzer] * time_step
        
        H2StorageSize[s in SCENARIO, r in REGION, h in PERIOD],
            H2StorageLevel[s, r, h] <= Capacity[r, :H2Storage]

        H2StorageBalance[s in SCENARIO, r in REGION, h in PERIOD],
            H2StorageLevel[s, r, h] <= H2StorageLevel[s, r, h>1 ? h-1 : length(PERIOD)] + 
            + Electricity[s,r,:Electrolyzer,h] * eta[:Electrolyzer] - Electricity[s, r, :H2GT, h] / eta[:H2GT]

        # SYSTEM ENERGY BALANCE
        ElecDemand[s in SCENARIO, r in REGION, h in PERIOD],
            sum(Electricity[s, r, p, h] for p in PLANT) +
            - Electricity[s, r, :Battery, h] - Electricity[s, r, :PSHopenPump, h] - Electricity[s, r, :PSHclosedPump, h] - Electricity[s, r, :Electrolyzer, h] + 
            + Electricity[s, r, :Inverter, h] + Electricity[s, r, :PSHopenTurb, h] + Electricity[s, r, :PSHclosedTurb, h]  + Electricity[s, r, :H2GT, h] + 
            + sum((1- loss_per_K_Km)^(distance[r1, r] / 1000) * Transmission[s, r1, r, h] for r1 in REGION if valid_links[r1, r]) +
            - sum(Transmission[s, r, r1, h] for r1 in REGION if valid_links[r, r1]) >= load[s, r, h] * time_step - SheddedLoad[s, r, h]

        SheddedLoadCap[s in SCENARIO, r in REGION, h in PERIOD],
            SheddedLoad[s, r, h] <= load[s, r, h] * time_step * load_shedding_ratio

        SystemTotalEmissions[s in SCENARIO],
            TotalEmissions[s] == 8760 /(time_step * no_periods) * sum(Electricity[s, r, p, h]/eta[p]*emissionfactor[p] for r in REGION, p in TECH, h in PERIOD) # ton CO2

        # CARBON CAP
        CarbonCap[s in SCENARIO],
		    TotalEmissions[s] <= carbon_cap * sum(load[s, r, h] * time_step - SheddedLoad[s, r, h] for r in REGION, h in PERIOD)    # carbon_cap in ton/MWh
        
        SystemOperationalCost[s in SCENARIO],
            OperationalCost[s] == 8760 /(time_step * no_periods) * (sum(Electricity[s, r, p, h]*(fuel_cost[p]/eta[p] + var_cost[p]) for r in REGION, p in TECH, h in PERIOD))

        SystemFixedCost[s in SCENARIO],
            FixedCost[s] == sum(Capacity[r, p]*fixed_cost[p] for r in REGION, p in TECH)

        SystemInvestmentCost,
            InvestmentCost == sum(Capacity[r, p]*inv_cost[p]*crf[p] for r in REGION, p in TECH) +
                           + sum(TransmissionCapacity[r, r1]*distance[r, r1] for r in REGION, r1 in REGION if r1 > r && valid_links[r, r1])*transmissioncost*crf_t
            
        SystemSheddedLoad[s in SCENARIO],
            TotalSheddedLoadCost[s] == load_shedding_cost * 8760 /(time_step * no_periods) * sum(SheddedLoad[s, r, h] for r in REGION, h in PERIOD)

    end #constraints

    @objective m Min begin
        InvestmentCost + sum(prob[s]*(OperationalCost[s] + FixedCost[s] + TotalSheddedLoadCost[s]) for s in SCENARIO)
    end
    return (;m, Capacity, Electricity, TransmissionCapacity, TotalEmissions, OperationalCost, FixedCost, InvestmentCost, TotalSheddedLoadCost, PlannedOutage)
end 

#//////////////////////////////////////////////////////////////////////////////////////////////////
"""
Build_Simulation_Model(Capacity_r, TransmissionCapacity_r, problem, input, simulation_data)

Construct a deterministic simulation model using fixed capacities from the stochastic solution.
Used only when `problem.simulate_results = true`.
- `Capacity_r`, `TransmissionCapacity_r` come from the solved stochastic model
- `simulation_data` contains time-series for a single historical year
Returns the model and variables needed to collect simulation outputs (Electricity, TotalEmissions, costs, etc.).
"""
function Build_Simulation_Model(Capacity_r, TransmissionCapacity_r, problem, input, simulation_data)
    println("\nBuilding models...")
    @unpack REGION, PLANT, TECH, PERIOD, no_periods, no_regions, no_plants, no_techs, inv_cost, fixed_cost, var_cost, fuel_cost, eta,
    emissionfactor, crf, maxcap, hydroreservoir, PSopenReservoir, PSclosedReservoir, min_reservoir_level, transmissioncost, distance, valid_links, loss_per_K_Km, crf_t = input 
    @unpack cf, load, res_inflow, ror_inflow, PS_inflow = simulation_data
    @unpack carbon_cap, time_step, load_shedding_cost, loss_of_load_penalty, load_shedding_ratio, planned_outage_rate = problem

    m = Model(Gurobi.Optimizer)
    set_optimizer_attributes(m, "Threads" => 0, "Method"=> 2, "Crossover"=> 0, "TimeLimit" => 10000)
      
    @variables m begin
        OperationalCost                                           >= 0        # €
        FixedCost                                                 >= 0        # €
        TotalSheddedLoadCost                                      >= 0        # €
        TotalLoadLossCost                                         >= 0        # €
        TotalEmissions                                            >= 0        # ton CO2
        InvestmentCost                                            >= 0        # €
        Electricity[r in REGION, p in TECH, h in PERIOD]          >= 0        # MWh/h
        SheddedLoad[r in REGION, h in PERIOD]                     >= 0        # MWh/h
        ChargeLevel[r in REGION, h in PERIOD]                     >= 0        # MWh
        ReservoirLevel[r in REGION, h in PERIOD]                  >= 0        # MWh
        PSopenLevel[r in REGION, h in PERIOD]                     >= 0        # MWh
        PSclosedLevel[r in REGION, h in PERIOD]                   >= 0        # MWh   
        H2StorageLevel[r in REGION, h in PERIOD]                  >= 0        # MWh
        Transmission[r in REGION, r1 in REGION, h in PERIOD; valid_links[r, r1]]       >= 0        # MWh/h
        PlannedOutage[r in REGION, h in PERIOD]                   >= 0        # MW 
        LoadLoss[r in REGION, h in PERIOD]                        >= 0        # MW
    end     #variables
    
    @constraints m begin
        # ELECTRICITY GENERATION
        Generation_0[r in REGION, p in PLANT, h in PERIOD; p != :Nuclear],
            Electricity[r, p, h] <= Capacity_r[r, p] * cf[r, p, h] * time_step

        Generation_1[r in REGION, h in PERIOD],
            Electricity[r, :Nuclear, h] <= Capacity_r[r, :Nuclear] * time_step - PlannedOutage[r, h]

        # BATTERIES & INVERTER
        InverterCapacity[r in REGION, h in PERIOD], 
            Electricity[r, :Inverter, h]  + Electricity[r, :Battery, h] <= Capacity_r[r, :Inverter] * time_step
        
        StorageSize[r in REGION, h in PERIOD],
            ChargeLevel[r, h] <= Capacity_r[r, :Battery]

        ElecStorageBalance[r in REGION, h in PERIOD],
            ChargeLevel[r, h] <= ChargeLevel[r, h>1 ? h-1 : length(PERIOD)] + eta[:Inverter] * Electricity[r, :Battery, h]  +
                - Electricity[r, :Inverter, h]/eta[:Inverter]

        # ELECTRICITY TRANSMISSION
        ElecTransmission[r in REGION, r1 in REGION, h in PERIOD; r1 > r && valid_links[r, r1]],
        	Transmission[r, r1, h] + Transmission[r1, r, h] <= TransmissionCapacity_r[r, r1] * time_step

        # NUCLEAR
        Outage_Planned[r in REGION],
            sum(PlannedOutage[r, h] for h in PERIOD) == planned_outage_rate * no_periods * Capacity_r[r, :Nuclear] * time_step; 

        # HYDROPOWER RESERVOIR
        ReservoirBalance[r in REGION, h in PERIOD],
            ReservoirLevel[r, h] <= ReservoirLevel[r, h>1 ? h-1 : length(PERIOD)] + res_inflow[r, h] * time_step +
            - Electricity[r, :HydroRes, h] / eta[:HydroRes]

        ReservoirSize[r in REGION, h in PERIOD],
            ReservoirLevel[r, h] <= hydroreservoir[r] * 1e6

        MinReservoirLevel[r in REGION, h in PERIOD],
            ReservoirLevel[r, h] >= min_reservoir_level[r] * hydroreservoir[r] * 1e6

        # HYDROPOWER ROR
        HydroRoRGeneration[r in REGION, h in PERIOD],
            Electricity[r, :HydroRoR, h] <= ror_inflow[r, h] * time_step

        # PUMPED STORAGE HYDROPOWER
        PSopenBalance[r in REGION, h in PERIOD],
            PSopenLevel[r,h] <= PSopenLevel[r, h>1 ? h-1 : length(PERIOD)] + 
            + Electricity[r,:PSHopenPump,h] * eta[:PSHopenPump] - Electricity[r,:PSHopenTurb,h] / eta[:PSHopenTurb] + PS_inflow[r,h] * time_step
            
        PSclosedBalance[r in REGION, h in PERIOD],
            PSclosedLevel[r,h] <= PSclosedLevel[r, h>1 ? h-1 : length(PERIOD)] +
            + Electricity[r,:PSHclosedPump,h] * eta[:PSHclosedPump] - Electricity[r,:PSHclosedTurb,h] / eta[:PSHclosedTurb]
        
        
        PowerBoundsPSHopenTurb[r in REGION, h in PERIOD],
            Electricity[r,:PSHopenTurb,h] <= Capacity_r[r, :PSHopenTurb] * time_step

        PowerBoundsPSHopenPump[r in REGION, h in PERIOD],
            Electricity[r,:PSHopenPump,h] <= Capacity_r[r, :PSHopenPump] * time_step

        PowerBoundsPSHclosedTurb[r in REGION, h in PERIOD],
            Electricity[r,:PSHclosedTurb,h] <= Capacity_r[r, :PSHclosedTurb] * time_step

        PowerBoundsPSHclosedPump[r in REGION, h in PERIOD],
            Electricity[r,:PSHclosedPump,h] <= Capacity_r[r, :PSHclosedPump] * time_step
        

        PSopenReservoirSize[r in REGION, h in PERIOD],
            PSopenLevel[r, h] <= PSopenReservoir[r] * 1e6     # [MWh]

        PSclosedReservoirSize[r in REGION, h in PERIOD],
            PSclosedLevel[r, h] <= PSclosedReservoir[r] * 1e6     # [MWh]

            
        MinPSopenReservoirLevel[r in REGION, h in PERIOD],
            PSopenLevel[r, h] >= min_reservoir_level[r] * PSopenReservoir[r] * 1e6

        # HYDROGEN
        PowerBoundsH2GT[r in REGION, h in PERIOD],
			Electricity[r,:H2GT,h] <= Capacity_r[r,:H2GT] * time_step

        PowerBoundsElectrolyzer[r in REGION, h in PERIOD],
            Electricity[r,:Electrolyzer,h] * eta[:Electrolyzer] <= Capacity_r[r,:Electrolyzer] * time_step
        
        H2StorageSize[r in REGION, h in PERIOD],
            H2StorageLevel[r, h] <= Capacity_r[r, :H2Storage]

        H2StorageBalance[r in REGION, h in PERIOD],
            H2StorageLevel[r, h] <= H2StorageLevel[r, h>1 ? h-1 : length(PERIOD)] + 
            + Electricity[r,:Electrolyzer,h] * eta[:Electrolyzer] - Electricity[r, :H2GT, h] / eta[:H2GT]

        # SYSTEM ENERGY BALANCE
        ElecDemand[r in REGION, h in PERIOD],
            sum(Electricity[r, p, h] for p in PLANT) +
            - Electricity[r, :Battery, h] - Electricity[r, :PSHopenPump, h] - Electricity[r, :PSHclosedPump, h] - Electricity[r, :Electrolyzer, h] + 
            + Electricity[r, :Inverter, h] + Electricity[r, :PSHopenTurb, h] + Electricity[r, :PSHclosedTurb, h] + Electricity[r, :H2GT, h] +
            + sum((1- loss_per_K_Km)^(distance[r1, r] / 1000) * Transmission[r1, r, h] for r1 in REGION if valid_links[r1, r]) +
            - sum(Transmission[r, r1, h] for r1 in REGION if valid_links[r, r1]) >= load[r, h] * time_step - SheddedLoad[r, h] - LoadLoss[r, h]

        SheddedLoadCap[r in REGION, h in PERIOD],
            SheddedLoad[r, h] <= load[r, h] * time_step * load_shedding_ratio

        SystemTotalEmissions,
            TotalEmissions == 8760 /(time_step * no_periods) * sum(Electricity[r, p, h]/eta[p]*emissionfactor[p] for r in REGION, p in TECH, h in PERIOD)

        # CARBON CAP
        CarbonCap,
		    TotalEmissions <= carbon_cap * sum(load[r, h] * time_step - SheddedLoad[r, h] - LoadLoss[r,h] for r in REGION, h in PERIOD)

        SystemOperationalCost,
            OperationalCost == 8760 /(time_step * no_periods) * (sum(Electricity[r, p, h]*(fuel_cost[p]/eta[p] + var_cost[p]) for r in REGION, p in TECH, h in PERIOD))

        SystemFixedCost,
            FixedCost == sum(Capacity_r[r, p]*fixed_cost[p] for r in REGION, p in TECH)

        SystemInvestmentCost,
            InvestmentCost == sum(Capacity_r[r, p]*inv_cost[p]*crf[p] for r in REGION, p in TECH) +
                           + sum(TransmissionCapacity_r[r, r1]*distance[r, r1] for r in REGION, r1 in REGION if r1 > r && valid_links[r, r1])*transmissioncost*crf_t
        SystemSheddedLoad,
            TotalSheddedLoadCost == load_shedding_cost * 8760 /(time_step * no_periods) * sum(SheddedLoad[r, h] for r in REGION, h in PERIOD)

        # LOAD LOSS
        SystemTotalLoadLossCost,
            TotalLoadLossCost == loss_of_load_penalty * 8760 /(time_step * no_periods) * sum(LoadLoss[r, h] for r in REGION, h in PERIOD)

    end #constraints
    @objective m Min begin
        InvestmentCost + OperationalCost + FixedCost + TotalSheddedLoadCost + TotalLoadLossCost 
    end
    return (;m, Electricity, TotalEmissions, OperationalCost, FixedCost, InvestmentCost, TotalSheddedLoadCost, TotalLoadLossCost, PlannedOutage)
end 

#//////////////////////////////////////////////////////////////////////////////////////////////////
"""
RunStochasticModel(problem, input, scenario_data)

Builds and solves the stochastic JuMP model (calls `Build_Stochastic_Model`), checks solver termination,
and returns a compact named tuple with objective, capacities, dispatch, and cost/emissions results.
"""
function RunStochasticModel(problem, input, scenario_data)
    @unpack REGION, PLANT,TECH, PERIOD, no_regions, no_plants, no_techs, no_periods, valid_links = input
    @unpack SCENARIO, load, cf, prob = scenario_data
    @unpack storage, transmission, nuclear, time_step, planned_outage_rate = problem
    model = Build_Stochastic_Model(problem, input, scenario_data)
    @unpack m, Capacity, Electricity, TransmissionCapacity, TotalEmissions, OperationalCost, InvestmentCost, FixedCost, TotalSheddedLoadCost, PlannedOutage   = model
    println("\nSolving model...")
    optimize!(m)

    ts = termination_status(m)      # IF ERROR: comment out this line and the if block below
    if ts == MOI.OPTIMAL
        println("\nSolve status: Optimal")
    elseif ts == MOI.TIME_LIMIT && has_values(m)
        println("\nSolve status: Reached the time-limit (feasible solution available)")
    else
        error("The model was not solved correctly: termination status = $(ts)")
    end

    Cost_r = objective_value(m)/1e6 
    Capacity_r = value.(Capacity)
    Electricity_r = value.(Electricity)
    TransmissionCapacity_r = value.(TransmissionCapacity)
    TotalEmissions_r = value.(TotalEmissions)
    TotalSheddedLoadCost_r = value.(TotalSheddedLoadCost)
    OperationalCost_r = value.(OperationalCost)
    FixedCost_r = value.(FixedCost)
    InvestmentCost_r = value.(InvestmentCost) 
    PlannedOutage_r = value.(PlannedOutage) 

    # Free memory
    m = nothing

    return (; status = ts, Cost_r, Capacity_r, Electricity_r, TransmissionCapacity_r, TotalEmissions_r, TotalSheddedLoadCost_r, OperationalCost_r, FixedCost_r, InvestmentCost_r, PlannedOutage_r)
end

#//////////////////////////////////////////////////////////////////////////////////////////////////
"""
RunSimulationModel(title, SELECTEDYEARS, Capacity_r, TransmissionCapacity_r, problem, input, time_series_data)

Run deterministic simulations across `SELECTEDYEARS` using fixed capacities. Returns averages and a table for reporting.
Only used when `problem.simulate_results = true`.
"""
function RunSimulationModel(title, SELECTEDYEARS, Capacity_r, TransmissionCapacity_r, problem, input, time_series_data)
    @unpack load_shedding_cost, loss_of_load_penalty, time_step = problem
    @unpack simulated_load = time_series_data
    result = []

    for s in SELECTEDYEARS
        TotalLoad_r = sum(simulated_load[s,:,:]) * time_step
        simulation_data = prepare_simulation_data(problem, input, time_series_data, s)
                                                  
        model = Build_Simulation_Model(Capacity_r, TransmissionCapacity_r, problem, input, simulation_data)
        @unpack m, Electricity, TotalEmissions, OperationalCost, FixedCost, InvestmentCost, TotalSheddedLoadCost, TotalLoadLossCost = model
        println("\nSolving simulation model (simulation year $(s+1978))...")
        optimize!(m)

        # Collect simulation results
        ObjVal_r = objective_value(m) / 1e6
        TotalCosts_r = (value.(InvestmentCost) + value.(OperationalCost) + value.(FixedCost) + value.(TotalSheddedLoadCost) + value.(TotalLoadLossCost) ) /1e6
        TotalCostsWithoutLoadLoss_r = (value.(InvestmentCost) + value.(OperationalCost) + value.(FixedCost) + value.(TotalSheddedLoadCost)) / 1e6 
        InvestmentCost_r = value.(InvestmentCost) / 1e6
        OperationalCost_r = value.(OperationalCost) / 1e6
        FixedCost_r = value.(FixedCost) / 1e6
        TotalEmissions_r = value.(TotalEmissions) / 1e6
        TotalSheddedLoadCost_r = value.(TotalSheddedLoadCost) / 1e6
        TotalLoadLossCost_r = value.(TotalLoadLossCost) / 1e6
        SheddedLoad_r = value.(TotalSheddedLoadCost) / load_shedding_cost / 1e6 
        LoadLoss_r = value.(TotalLoadLossCost) / loss_of_load_penalty / 1e6 
        SatisfiedLoad_r = (TotalLoad_r - value.(TotalSheddedLoadCost) / load_shedding_cost - value.(TotalLoadLossCost) / loss_of_load_penalty ) / 1e6
        UnitProductionCost_r = TotalCostsWithoutLoadLoss_r / SatisfiedLoad_r
      
        # Append results to the result array
        push!(result, (ObjVal_r, TotalCosts_r, TotalCostsWithoutLoadLoss_r, InvestmentCost_r, FixedCost_r, OperationalCost_r, TotalEmissions_r, TotalSheddedLoadCost_r, TotalLoadLossCost_r, SatisfiedLoad_r, SheddedLoad_r, LoadLoss_r, UnitProductionCost_r)) 
        
        # Reset the model (optional, depending on your use case)
        m = nothing
    end
    
    # Convert the result array to a DataFrame
    df = DataFrame(result)
    
    # Convert the DataFrame to a NamedArray
    named_array = NamedArray(Matrix(df), (1:size(df, 1), names(df)))

    # Calculate the averages for each column
    averages = mean(named_array, dims=1)  # Compute mean along the first dimension (rows)
    averages = vec(averages)  # Flatten into a 1D vector for easier access

    # Create a named tuple for averages
    AverageObjVal = averages[1]
    AverageCosts = averages[2]
    AverageTotalCostsWithoutLoadLoss = averages[3]
    AverageInvestmentCost = averages[4]
    AverageFixedCost = averages[5]
    AverageOperationalCost = averages[6]
    AverageTotalEmissions = averages[7]
    AverageTotalSheddedLoadCost = averages[8]
    AverageTotalLoadLossCost = averages[9]
    AverageSatisfiedLoad = averages[10]
    AverageSheddedLoad = averages[11]
    AverageLoadLoss = averages[12]
    AverageUnitProductionCost = averages[13]
    
    # Add the averages row as the first row (so it becomes first column after transpose)
    extended_array = vcat(reshape(averages, 1, :), named_array)  # Prepend averages as first row
    
    # Update the row names to include "Average" as the first row
    new_row_names = vcat(["Average"], 1:size(df, 1))
    extended_named_array = NamedArray(extended_array, (new_row_names, names(df)))

    # Transpose to get final table layout (averages is now first column)
    transposed_array = extended_named_array'
    
    # Prepare column headers with "Average" first
    column_headers = vcat("Average", "Year " .* string.(SELECTEDYEARS .+(1979 - 1)))

    # Prepare the table for saving
    table = [(
        title, 
        transposed_array,
        column_headers,
        ["Objective value",
        "Total costs (M€)",
        "Total costs without load loss (M€)",
        "Investment cost (M€)",
        "Fixed cost (M€)",
        "Operational cost (M€)",
        "CO2 emissions (Mt)",
        "Load shedding cost (M€)",
        "Load loss cost (M€)",
        "Satisfied load (TWh)",
        "Shedded Load (TWh)",
        "Load loss (TWh)",
        "Unit production cost (€/MWh)"]
    )]
    
    # Return the named tuple of averages and the table
    return (; AverageObjVal, 
    AverageCosts, 
    AverageTotalCostsWithoutLoadLoss, 
    AverageInvestmentCost, 
    AverageFixedCost, 
    AverageOperationalCost, 
    AverageTotalEmissions, 
    AverageTotalSheddedLoadCost, 
    AverageTotalLoadLossCost, 
    AverageSatisfiedLoad, 
    AverageSheddedLoad, 
    AverageLoadLoss, 
    AverageUnitProductionCost, 
    table)
end

#//////////////////////////////////////////////////////////////////////////////////////////////////
"""
SolveStochasticModel(problem, input, scenario_data, time_series_data)

High-level wrapper that:
1. Solves the stochastic optimization model
2. Processes results into summary tables (via `GetTableSummary`)
3. Optionally runs deterministic simulations and appends simulation tables
Returns a named tuple with `tables` and the raw `solution` results.
"""
function SolveStochasticModel(problem, input, scenario_data, time_series_data)
    # Here we solve a model based on scenario data 
    tables = []
    solution = RunStochasticModel(problem, input, scenario_data)
    @unpack Capacity_r, TransmissionCapacity_r = solution
    solution_summary = GetTableSummary(problem, input, scenario_data, solution)
    #PlotSolution(solution_summary, problem, input, scenario_data)
    append!(tables, solution_summary.tables)
    SELECTEDYEARS = time_series_data.SIMULATION_YEARS
    if problem.simulate_results  
        simulation_output = RunSimulationModel("Simulation Results:", SELECTEDYEARS, Capacity_r, TransmissionCapacity_r, problem, input, time_series_data)
        append!(tables, simulation_output.table)
    end
    return (; tables, solution)
end